### ISSUE TITLE
no sensor data

### ISSUE THREAD

**Issue by noisy44** [alexiosc/ecofrog#3] opened 2023-08-09 11:28 UTC
The query of the data seems to work for me, at least the hub of the sensor is queried correctly. However, no sensor data arrives, what could that be? I don't get an error message

`Debug-Log

TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'config_entries'
2023-08-09 13:16:50.724 DEBUG (SyncWorker_4) [custom_components.ecofrog.coordinator] Worked around EcoFrog doubly-encoded JSON: [{'DeviceID': '5155951', 'DeviceName': 'IBC Tank', 'Medium': 'Wasser', 'LastUpdate': '8/9/2023 7:30:02 AM', 'MaxVolume': '2000', 'ActualVolume': '1560', 'ActualVolumePercent': '78', 'Battery': '2.7', 'Temperature': '62', 'MessData': '23'}]
2023-08-09 13:16:50.724 DEBUG (SyncWorker_4) [custom_components.ecofrog.coordinator] Coordinator data out: [{'DeviceID': '5155951', 'DeviceName': 'IBC Tank', 'Medium': 'Wasser', 'LastUpdate': '8/9/2023 7:30:02 AM', 'MaxVolume': '2000', 'ActualVolume': '1560', 'ActualVolumePercent': '78', 'Battery': '2.7', 'Temperature': '62', 'MessData': '23', 'last_update_successful': True, 'last_update': datetime.datetime(2023, 8, 9, 7, 30, 2)}]
2023-08-09 13:16:50.823 DEBUG (MainThread) [custom_components.ecofrog.coordinator] Finished fetching ecofrog data in 0.222 seconds (success: True)`

**Comment by daltdtot** [comment] 2023-08-16 10:46
Same error, I tried to remove he custom component and added again, here more debug logs:

2023-08-16 12:32:02.638 DEBUG (SyncWorker_7) [custom_components.ecofrog.config_flow] Authenticating: "{\"DeviceResponse\":[{\"DeviceID\":\"203\",\"DeviceName\":\"Sgo exchange device\",\"Medium\":\"Water\",\"LastUpdate\":\"8/16/2023 6:15:02 AM\",\"MaxVolume\":\"30000\",\"ActualVolume\":\"2556\",\"ActualVolumePercent\":\"10\",\"Battery\":\"3\",\"Temperature\":\"73\",\"MessData\":\"237\"}]}"
2023-08-16 12:32:02.785 DEBUG (SyncWorker_3) [custom_components.ecofrog.coordinator] Worked around EcoFrog doubly-encoded JSON: [{'DeviceID': '203', 'DeviceName': 'Sgo exchange device', 'Medium': 'Water', 'LastUpdate': '8/16/2023 6:15:02 AM', 'MaxVolume': '30000', 'ActualVolume': '2556', 'ActualVolumePercent': '10', 'Battery': '3', 'Temperature': '73', 'MessData': '237'}]
2023-08-16 12:32:02.786 DEBUG (SyncWorker_3) [custom_components.ecofrog.coordinator] Coordinator data out: [{'DeviceID': '203', 'DeviceName': 'Sgo exchange device', 'Medium': 'Water', 'LastUpdate': '8/16/2023 6:15:02 AM', 'MaxVolume': '30000', 'ActualVolume': '2556', 'ActualVolumePercent': '10', 'Battery': '3', 'Temperature': '73', 'MessData': '237', 'last_update_successful': True, 'last_update': datetime.datetime(2023, 8, 16, 6, 15, 2)}]
2023-08-16 12:32:02.791 DEBUG (MainThread) [custom_components.ecofrog.coordinator] Finished fetching ecofrog data in 0.149 seconds (success: True)
2023-08-16 12:32:02.793 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor Volume init-time value 2556
2023-08-16 12:32:02.793 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor ecofrog203_volume initialised
2023-08-16 12:32:02.794 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor Max Volume init-time value 30000
2023-08-16 12:32:02.794 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor ecofrog203_maxvolume initialised
2023-08-16 12:32:02.794 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor Percent Full init-time value 10
2023-08-16 12:32:02.794 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor ecofrog203_full initialised
2023-08-16 12:32:02.794 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor Battery init-time value 3.0
2023-08-16 12:32:02.794 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor ecofrog203_battery initialised
2023-08-16 12:32:02.795 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor Temperature init-time value 73
2023-08-16 12:32:02.795 DEBUG (MainThread) [custom_components.ecofrog.sensor] Sensor ecofrog203_temperature initialised
2023-08-16 12:32:02.798 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ecofrog
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'config_entries'
2023-08-16 12:32:02.809 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ecofrog platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'config_entries'
2023-08-16 12:32:02.953 DEBUG (SyncWorker_0) [custom_components.ecofrog.coordinator] Worked around EcoFrog doubly-encoded JSON: [{'DeviceID': '203', 'DeviceName': 'Sgo exchange device', 'Medium': 'Water', 'LastUpdate': '8/16/2023 6:15:02 AM', 'MaxVolume': '30000', 'ActualVolume': '2556', 'ActualVolumePercent': '10', 'Battery': '3', 'Temperature': '73', 'MessData': '237'}]
2023-08-16 12:32:02.953 DEBUG (SyncWorker_0) [custom_components.ecofrog.coordinator] Coordinator data out: [{'DeviceID': '203', 'DeviceName': 'Sgo exchange device', 'Medium': 'Water', 'LastUpdate': '8/16/2023 6:15:02 AM', 'MaxVolume': '30000', 'ActualVolume': '2556', 'ActualVolumePercent': '10', 'Battery': '3', 'Temperature': '73', 'MessData': '237', 'last_update_successful': True, 'last_update': datetime.datetime(2023, 8, 16, 6, 15, 2)}]
2023-08-16 12:32:02.957 DEBUG (MainThread) [custom_components.ecofrog.coordinator] Finished fetching ecofrog data in 0.159 seconds (success: True)

**Comment by thomail** [comment] 2023-08-29 08:17
@alexiosc: don't want to bother you, but winter is coming! any chance you can fix this issue?

**Comment by alexiosc** [comment] 2023-09-24 05:10
Sorry for the delays, I've been away and not minding my own diesel tank, but now that Winter Is Coming I'm getting this sorted ASAP. I know what the problem is (Home Assistant deprecated some functionality that just so happened to be in its own tutorial, bletch) and I'm getting close to a solution.

**Comment by alexiosc** [comment] 2023-09-24 05:43
It's working for me now, I'm going to push the update so you guys can try it, and let me know if it fails!

![image](https://github.com/alexiosc/ecofrog/assets/20264881/ece2533d-6ff3-4141-835d-895c5f3e58b1)

**Comment by alexiosc** [comment] 2023-09-24 05:59
Okay, try updating to version 0.3 via HACS. I just:

1. Undid all my fixes and restarted: the sensor turned back to being `Unavailable`.
2. Pushed the fixes to github.
3. Published version 0.3.
4. Updated to version 0.3 via HACS and restarted: sensor returned data again.

So it looks like the HACS-available version of the integration should work for others too. Please check and let me know!

**Comment by thomail** [comment] 2023-09-25 04:43
Thank you very much @alexiosc! Updated thru HACS and it works again!

**Comment by daltdtot** [comment] 2023-09-25 12:18
Thanks @alexiosc!! all working again.

**Comment by alexiosc** [comment] 2023-09-26 05:50
Fantastic! Closing the issue!

**Closed as completed by alexiosc** 2023-09-26 05:50 UTC
